spring:
  config:
    activate:
      on-profile: oauth_dev

  oauth2:
    client:
      provider:
        naver:
          login-url: "https://nid.naver.com/oauth2.0/authorize"
          token-url: "https://nid.naver.com/oauth2.0/token"
          me-url: "https://openapi.naver.com/v1/nid/me"
      registration:
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}
          authorization-grant-type: authorization_code
          redirect-uri: "http://${BASE_URL}/api/auth/oauth/callback/naver"
